### ISSUE TITLE
Export scans to HDF5

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polar_instrument#20]
Implement the HDF5 callback to all scans (https://github.com/APS-4ID-POLAR/polar_instrument/blob/main/instrument/callbacks/master_file_writer.py). Will probably need to standardize the way that image files get named and linked. In the flyscan demo it was in the plan:  https://github.com/APS-4ID-POLAR/polar_instrument/blob/4e925e9a151620c773c359471bedba843117a3dd/instrument/plans/flyscan_demo.py#L383

**Comment by prjemian** [comment]
Following this [comment](https://github.com/APS-4ID-POLAR/polar_instrument/issues/19#issuecomment-2295392402), I suggest adding a common function that defines the name of the HDF5 file.  The function (does not have to be a plan since it sounds like pure Python to me) would build the name based on your local standard conventions.

**Comment by gfabbris** [comment]
Closed by #37.
