### ISSUE TITLE
Duplicated specwriter subscription

### ISSUE THREAD

**Issue by gfabbris** [APS-4ID-POLAR/polar_instrument#29]
We have a duplicated specwriter `RE` subscription during startup:

https://github.com/APS-4ID-POLAR/polar_instrument/blob/19dad53865917db7f0526ec42823c97040078ac4/instrument/collection.py#L130

https://github.com/APS-4ID-POLAR/polar_instrument/blob/19dad53865917db7f0526ec42823c97040078ac4/instrument/framework/callbacks.py#L32

@prjemian: This is a detail, but is there any "standard practice" for where to have this?

**Comment by prjemian** [comment]
Funny.  Was just looking at this situation today. Not sure if there is a standard way.  [Here's what I'd do](https://github.com/prjemian/instrument_template/blob/35adea53738106b2bdf0873315179f1eb6e280f5/src/instrument/callbacks/__init__.py#L5-L9).  In short:

```py
if iconfig.get("NEXUS_DATA_FILES", False):
    from .nexus_data_file_writer import *  # noqa

if iconfig.get("SPEC_DATA_FILES", False):
    from .spec_data_file_writer import *  # noqa
```

 `RE` _callback_ subscriptions require a bit of consideration.  They need the `RE` object already defined, and they need the callback defined as configured by the instrument.  Because of these factors, it seems easiest to import any configured callbacks from the `instrument/callbacks/__init__.py` file, as shown above.

BTW, we're working on an overhaul of the instrument template for APS beamlines.  We have two propositions now:

- [in-place at 8-ID](https://github.com/aps-8id-dys/bluesky) (but cannot run queueserver)
- [my working prototype](https://github.com/prjemian/instrument_template) (OK for console, notebook, QS, and scripts)

**Comment by prjemian** [comment]
This demo uses a [re-arranged `iconfig.yml` file](https://github.com/prjemian/instrument_template/blob/dc60ecbd17fea6fcd6b70d1b97710b8cf1800ba0/src/instrument/configs/iconfig.yml#L3-L4).

Using a version number to keep track.

```yaml
# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0
```

**Comment by prjemian** [comment]
### Summary recommendation

Don't subscribe callbacks in `collection`.  Instead, do it in `callbacks/__init__.py`.  If you have `iconfig` settings, apply them as shown above.

**Comment by gfabbris** [comment]
Sounds good. I like the organization of your prototype, will try to migrate it to that.
